/* ========================================
   spreads.js — 10 Classic Tarot Spreads (Bilingual)
   ======================================== */

const TAROT_SPREADS = [
  {
    id: 'celtic-cross', name: 'Celtic Cross', nameZh: '凯尔特十字', icon: '✧', cardCount: 10,
    shortDesc: 'The most comprehensive classic spread', shortDescZh: '最经典全面的牌阵',
    description: 'The Celtic Cross is the most renowned tarot spread. Ten cards cross-analyze from different dimensions, revealing the heart of the matter, past influences, future direction, and final outcome.',
    descriptionZh: '凯尔特十字是塔罗牌中最著名、最全面的牌阵。十张牌从不同维度交叉分析，揭示问题的核心、过去的影响、未来的走向以及最终结果。',
    suitableFor: ['人生困惑','重大决策','全面分析','年度运势'],
    positions: [
      { index:1, name:'Present', nameZh:'现状', description:'The heart of the matter', descriptionZh:'当前的核心情况和心态' },
      { index:2, name:'Challenge', nameZh:'阻碍', description:'What crosses you', descriptionZh:'横亘在前的障碍或挑战' },
      { index:3, name:'Root', nameZh:'根源', description:'The foundation beneath', descriptionZh:'问题深处的根本原因' },
      { index:4, name:'Past', nameZh:'过去', description:'What has passed but still echoes', descriptionZh:'已过去但仍产生影响的因素' },
      { index:5, name:'Crown', nameZh:'目标', description:'Your highest aspiration', descriptionZh:'心中的理想结果或期望' },
      { index:6, name:'Near Future', nameZh:'近未来', description:'What approaches soon', descriptionZh:'不久的将来会发生的事' },
      { index:7, name:'Self', nameZh:'态度', description:'Your true stance', descriptionZh:'你对这件事的真实态度' },
      { index:8, name:'Environment', nameZh:'环境', description:'The world around you', descriptionZh:'周围环境和他人对你的影响' },
      { index:9, name:'Hopes & Fears', nameZh:'希望与恐惧', description:'What stirs within', descriptionZh:'内心深处的期待和担忧' },
      { index:10, name:'Outcome', nameZh:'结果', description:'Where this path leads', descriptionZh:'最终可能呈现的结果' },
    ],
  },
  {
    id: 'three-card', name: 'Three Cards', nameZh: '三张牌', icon: '◇', cardCount: 3,
    shortDesc: 'Past · Present · Future', shortDescZh: '过去 · 现在 · 未来',
    description: 'Three cards laid in a timeline reveal the flow of past influence, present state, and future direction.',
    descriptionZh: '三张牌按时间线解读过去的影响、现在的状态和未来的走向。适合日常占卜。',
    suitableFor: ['日常占卜','快速指引','简单决策'],
    positions: [
      { index:1, name:'Past', nameZh:'过去', description:'What shaped this moment', descriptionZh:'已经发生并影响当下的事件' },
      { index:2, name:'Present', nameZh:'现在', description:'The current state', descriptionZh:'当前的状态和处境' },
      { index:3, name:'Future', nameZh:'未来', description:'What unfolds ahead', descriptionZh:'未来的发展趋势' },
    ],
  },
  {
    id: 'hexagram', name: 'Hexagram', nameZh: '六芒星', icon: '⬡', cardCount: 7,
    shortDesc: 'Deep causal analysis', shortDescZh: '深入分析事件因果',
    description: 'Seven cards in a hexagram star analyze past, present, future, approach, environment, inner self, and outcome.',
    descriptionZh: '七张牌排列成六芒星形状，从七个角度全面分析问题。',
    suitableFor: ['事件分析','关系问题','决策参考'],
    positions: [
      { index:1, name:'Past', nameZh:'过去', description:'Root of the matter', descriptionZh:'事件的历史根源' },
      { index:2, name:'Present', nameZh:'现在', description:'The current reality', descriptionZh:'当前的实际状况' },
      { index:3, name:'Future', nameZh:'未来', description:'Natural progression', descriptionZh:'自然发展的趋势' },
      { index:4, name:'Action', nameZh:'对策', description:'How to respond', descriptionZh:'应采取的行动方案' },
      { index:5, name:'Environment', nameZh:'环境', description:'External influences', descriptionZh:'周围人事物的影响' },
      { index:6, name:'Inner Self', nameZh:'内心', description:'What your soul whispers', descriptionZh:'潜意识的渴望或恐惧' },
      { index:7, name:'Outcome', nameZh:'结果', description:'The final shape', descriptionZh:'最终的结局走向' },
    ],
  },
  {
    id: 'four-elements', name: 'Four Elements', nameZh: '四元素', icon: '⊹', cardCount: 4,
    shortDesc: 'Fire · Water · Air · Earth', shortDescZh: '火 · 水 · 风 · 土',
    description: 'Four cards representing elemental forces: Fire (action), Water (emotion), Air (thought), Earth (matter).',
    descriptionZh: '以火水风土四大元素为框架，分析问题在不同能量层面的表现。',
    suitableFor: ['自我探索','能量平衡','全面审视'],
    positions: [
      { index:1, name:'Fire', nameZh:'火', description:'Action & passion', descriptionZh:'行动力和热情所在' },
      { index:2, name:'Water', nameZh:'水', description:'Emotion & intuition', descriptionZh:'情感和直觉的流向' },
      { index:3, name:'Air', nameZh:'风', description:'Thought & communication', descriptionZh:'思想和沟通的状态' },
      { index:4, name:'Earth', nameZh:'土', description:'Matter & reality', descriptionZh:'物质与现实层面的状况' },
    ],
  },
  {
    id: 'zodiac', name: 'Zodiac Wheel', nameZh: '黄道十二宫', icon: '◎', cardCount: 12,
    shortDesc: 'A full life panorama', shortDescZh: '全方位人生透视',
    description: 'Twelve cards mapped to the zodiac houses, covering every domain of life.',
    descriptionZh: '以黄道十二宫为框架，从十二个人生领域进行全面解读。适合年度大占卜。',
    suitableFor: ['年度占卜','人生规划','全方位分析'],
    positions: [
      { index:1, name:'Self', nameZh:'自我', description:'Identity & direction', descriptionZh:'个人形象与方向' },
      { index:2, name:'Wealth', nameZh:'财富', description:'Values & resources', descriptionZh:'金钱与价值观念' },
      { index:3, name:'Communication', nameZh:'沟通', description:'Learning & expression', descriptionZh:'交流、学习与思维' },
      { index:4, name:'Home', nameZh:'家庭', description:'Roots & sanctuary', descriptionZh:'家庭环境与根源' },
      { index:5, name:'Love', nameZh:'爱情', description:'Creativity & joy', descriptionZh:'恋爱、创造力与快乐' },
      { index:6, name:'Work', nameZh:'工作', description:'Daily life & health', descriptionZh:'日常工作与健康' },
      { index:7, name:'Partnership', nameZh:'关系', description:'Union & balance', descriptionZh:'伴侣关系与合作' },
      { index:8, name:'Transformation', nameZh:'深层', description:'Depth & rebirth', descriptionZh:'深层心理与转变' },
      { index:9, name:'Belief', nameZh:'信念', description:'Philosophy & journey', descriptionZh:'信仰、哲学与远行' },
      { index:10, name:'Career', nameZh:'事业', description:'Vocation & legacy', descriptionZh:'社会地位与事业成就' },
      { index:11, name:'Community', nameZh:'社交', description:'Friends & ideals', descriptionZh:'朋友、团体与理想' },
      { index:12, name:'Unconscious', nameZh:'潜意识', description:'Hidden truths', descriptionZh:'隐藏的因果与灵性' },
    ],
  },
  {
    id: 'horseshoe', name: 'Horseshoe', nameZh: '马蹄铁', icon: '∩', cardCount: 7,
    shortDesc: 'Classic English school spread', shortDescZh: '经典英国学派牌阵',
    description: 'Seven cards in a horseshoe arc from past to future, external to internal.',
    descriptionZh: '七张牌呈马蹄形排列，从过去到未来、从外界影响到内心期待，循序渐进。',
    suitableFor: ['时间线问题','发展趋势','期望分析'],
    positions: [
      { index:1, name:'Past', nameZh:'过去', description:'Historical context', descriptionZh:'问题的历史背景' },
      { index:2, name:'Present', nameZh:'现在', description:'The core now', descriptionZh:'当下的核心状况' },
      { index:3, name:'Hidden', nameZh:'隐藏影响', description:'Unseen currents', descriptionZh:'尚未显现的潜在因素' },
      { index:4, name:'Obstacle', nameZh:'障碍', description:'What blocks the way', descriptionZh:'需要克服的困难' },
      { index:5, name:'External', nameZh:'外界态度', description:'How others perceive', descriptionZh:'他人对此事的看法' },
      { index:6, name:'Advice', nameZh:'建议', description:'The best course', descriptionZh:'最佳的行动方向' },
      { index:7, name:'Outcome', nameZh:'最终结果', description:'The likely end', descriptionZh:'最可能的结局' },
    ],
  },
  {
    id: 'relationship', name: 'Relationship', nameZh: '关系牌阵', icon: '♥', cardCount: 7,
    shortDesc: 'See into any relationship', shortDescZh: '透视两人关系',
    description: 'A spread for relationships — romantic, platonic, or professional.',
    descriptionZh: '专门用于分析两性关系或人际关系。从你、对方、关系现状、障碍、未来等角度深度剖析。',
    suitableFor: ['恋爱关系','婚姻占卜','人际关系','合作评估'],
    positions: [
      { index:1, name:'Your Feelings', nameZh:'你的感受', description:'What you truly feel', descriptionZh:'你在这段关系中的真实感受' },
      { index:2, name:'Their Feelings', nameZh:'对方的感受', description:'What they truly feel', descriptionZh:'对方在这段关系中的心态' },
      { index:3, name:'The Bond', nameZh:'关系现状', description:'The connection between you', descriptionZh:'当前关系的核心状态' },
      { index:4, name:'Obstacle', nameZh:'障碍', description:'What stands between you', descriptionZh:'关系中存在的问题或阻碍' },
      { index:5, name:'Common Ground', nameZh:'连接点', description:'What holds you together', descriptionZh:'维系你们关系的纽带' },
      { index:6, name:'Advice', nameZh:'建议', description:'How to nurture this bond', descriptionZh:'改善关系的建议' },
      { index:7, name:'Future', nameZh:'未来发展', description:'Where this leads', descriptionZh:'关系的未来走向' },
    ],
  },
  {
    id: 'tree-of-life', name: 'Tree of Life', nameZh: '生命之树', icon: '𖧷', cardCount: 10,
    shortDesc: 'Kabbalistic spiritual spread', shortDescZh: '卡巴拉灵性牌阵',
    description: 'Based on the Kabbalistic Tree of Life, ten Sephiroth from material to divine.',
    descriptionZh: '源自卡巴拉生命之树的灵性牌阵，十个位置从物质世界到精神世界层层递进。',
    suitableFor: ['灵性探索','深层自我','人生意义','精神成长'],
    positions: [
      { index:1, name:'Kingdom', nameZh:'王国', description:'Physical manifestation', descriptionZh:'现实世界的具体表现' },
      { index:2, name:'Foundation', nameZh:'基础', description:'The bedrock beneath', descriptionZh:'问题的最底层基础' },
      { index:3, name:'Splendor', nameZh:'光辉', description:'Drive & action', descriptionZh:'行动力和驱动力' },
      { index:4, name:'Victory', nameZh:'胜利', description:'Emotion & feeling', descriptionZh:'感性与情绪的能量' },
      { index:5, name:'Beauty', nameZh:'美丽', description:'Balancing center', descriptionZh:'中心平衡点' },
      { index:6, name:'Severity', nameZh:'严厉', description:'Discipline & limit', descriptionZh:'规则、限制与纪律' },
      { index:7, name:'Mercy', nameZh:'慈悲', description:'Grace & expansion', descriptionZh:'恩典、慷慨与爱' },
      { index:8, name:'Understanding', nameZh:'理解', description:'Intuitive wisdom', descriptionZh:'深层理解与直觉智慧' },
      { index:9, name:'Wisdom', nameZh:'智慧', description:'Divine inspiration', descriptionZh:'更高的智慧与创造灵感' },
      { index:10, name:'Crown', nameZh:'王冠', description:'Ultimate unity', descriptionZh:'终极真相与宇宙连接' },
    ],
  },
  {
    id: 'choice', name: 'Crossroads', nameZh: '二选一', icon: '↔', cardCount: 5,
    shortDesc: 'A light at the fork in the road', shortDescZh: '两难抉择的明灯',
    description: 'When you face two paths, this spread illuminates each one.',
    descriptionZh: '面临两个选择的十字路口时，这个牌阵帮你看清每条路的风景和走向。',
    suitableFor: ['两难选择','职业决策','人生岔路'],
    positions: [
      { index:1, name:'Crossroads', nameZh:'当前状况', description:'Where you stand now', descriptionZh:'你此时此刻的处境' },
      { index:2, name:'Path A', nameZh:'选择A的走向', description:'Where the first path leads', descriptionZh:'选择第一个方向会如何发展' },
      { index:3, name:'Path B', nameZh:'选择B的走向', description:'Where the second path leads', descriptionZh:'选择第二个方向会如何发展' },
      { index:4, name:'Outcome A', nameZh:'选择A的结果', description:'The fruit of path A', descriptionZh:'第一个选择最终可能导致的结果' },
      { index:5, name:'Outcome B', nameZh:'选择B的结果', description:'The fruit of path B', descriptionZh:'第二个选择最终可能导致的结果' },
    ],
  },
  {
    id: 'single', name: 'Single Card', nameZh: '单张牌', icon: '◈', cardCount: 1,
    shortDesc: 'One card, one truth', shortDescZh: '每日一牌，简洁明心',
    description: 'The simplest form of divination. One card for daily guidance.',
    descriptionZh: '只抽一张牌，最简单直接的占卜方式。适合每日运势指引。',
    suitableFor: ['每日运势','冥想指引','简单回答'],
    positions: [
      { index:1, name:'Message', nameZh:'启示', description:'The most important message now', descriptionZh:'当前最重要的讯息' },
    ],
  },
];
